apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-api-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.adminApi.storage.size }}
  storageClassName: {{ .Values.adminApi.storage.class }}
