{{- if .Values.nats.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats.serviceAccountName" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- with .Values.nats.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
