apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-writer
spec:
  replicas: 1
  selector:
    matchLabels:
            {{- include "runtime.labels" . | nindent 6 }}
      app: mongo-writer
  template:
    metadata:
      labels:
              {{- include "runtime.labels" . | nindent 8 }}
        app: mongo-writer
    spec:
      serviceAccountName: kre-operator
      containers:
        - name: mongo-writer
          # TODO: This version should be fixed and the operator released in-sync with new mongo-writer changes
          image: konstellation/kre-mongo-writer:latest
          imagePullPolicy: {{ if .Values.developmentMode }}IfNotPresent{{ else }}Always{{ end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
