{{- if .Values.natsManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats-manager.serviceAccountName" . }}
  labels:
    {{- include "nats-manager.labels" . | nindent 4 }}
  {{- if .Values.natsManager.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.natsManager.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
