apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
  {{- with .Values.registry.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.registry.ingress.className }}
  {{- if .Values.registry.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.registry.host }}
      secretName: {{ .Values.registry.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.registry.host }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "registry.fullname" .}}
                port:
                  name: http
              {{- else }}
              serviceName: {{ include "registry.fullname" .}}
              servicePort: http
              {{- end }}
