{{- if and .Values.registry.config (not .Values.registry.configSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{ include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
    {{ .Values.registry.config | nindent 4 }}
{{- end }}
