stages:
  - test
  - quality
  - semantic-release
  - build
  - publish-image
  - semantic-release-helm
  - publish-gitlab-release
  - deploy

variables:
  # semantic-release uses GITLAB_TOKEN
  # gitlab-release uses GITLAB_ACCESS_TOKEN
  GITLAB_TOKEN: $GITLAB_ACCESS_TOKEN
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

.branch-rebased:
  stage: test
  image: igzgustavomarin/branch-ahead-of-master:latest
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
  script:
    - echo "Checking if $BRANCH_NAME is ahead of master"
    - branch-ahead-of-master
  only:
    refs:
      - branches
  except:
    refs:
      - master

.code-quality:
  stage: test
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/security-products/codequality:0.85.5"
  script:
    - cp $COMPONENT_PATH/.codeclimate.yml .
    - echo $COMPONENT_PATH
    - cat .codeclimate.yml
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - docker pull --quiet "$CODE_QUALITY_IMAGE"
    - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/report
      --volume /var/run/docker.sock:/var/run/docker.sock
      "$CODE_QUALITY_IMAGE" /report
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week
  dependencies: []
  only:
    refs:
      - merge_requests
      - master

.sonar-scanner:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd $COMPONENT_PATH
    - sonar-scanner
  only:
    - merge_requests
    - master

include:
  - local: admin-api/.gitlab-ci.yml
  - local: admin-ui/.gitlab-ci.yml
  - local: helm/.gitlab-ci.yml
  - local: operator/.gitlab-ci.yml
  - local: k8s-manager/.gitlab-ci.yml
  - local: runtime-api/.gitlab-ci.yml
  - local: runtime-entrypoint/.gitlab-ci.yml
