stages:
  - test
  - semantic-release
  - build
  - publish-image
  - semantic-release-helm
  - publish-gitlab-release
  - deploy

variables:
  # semantic-release uses GITLAB_TOKEN
  # gitlab-release uses GITLAB_ACCESS_TOKEN
  GITLAB_TOKEN: $GITLAB_ACCESS_TOKEN
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

.branch-rebased:
  stage: test
  image: igzgustavomarin/branch-ahead-of-master:latest
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
  script:
    - echo "Checking if $BRANCH_NAME is ahead of master"
    - branch-ahead-of-master
  only:
    refs:
      - branches
  except:
    refs:
      - master

release-helm-after-image:
  stage: semantic-release-helm
  image: node:10
  before_script:
    - npm install -g semantic-release semantic-release/gitlab
  script:
    - semantic-release -t helm-chart-v\${version}
  only:
    - tags
  except:
    - /^helm-chart-v\d*.\d*.\d*$/

include:
  - local: admin-api/.gitlab-ci.yml
  - local: admin-ui/.gitlab-ci.yml
  - local: helm/.gitlab-ci.yml
  - local: operator/.gitlab-ci.yml
  - local: k8s-resource-manager/.gitlab-ci.yml
