stages:
  - security
  - test
  - quality
  - semantic-release
  - build
  - publish-image
  - semantic-release-helm
  - publish-gitlab-release
  - deploy

variables:
  # semantic-release uses GITLAB_TOKEN
  # gitlab-release uses GITLAB_ACCESS_TOKEN
  GITLAB_TOKEN: $GITLAB_ACCESS_TOKEN
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

.branch-rebased:
  stage: test
  image: igzgustavomarin/branch-ahead-of-master:latest
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
  script:
    - echo "Checking if $BRANCH_NAME is ahead of master"
    - branch-ahead-of-master
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: always

.sonar-scanner:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd $COMPONENT_PATH
    - sonar-scanner
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

include:
  - local: admin-api/.gitlab-ci.yml
  - local: admin-ui/.gitlab-ci.yml
  - local: helm/.gitlab-ci.yml
  - local: operator/.gitlab-ci.yml
  - local: k8s-manager/.gitlab-ci.yml
  - local: runtime-api/.gitlab-ci.yml
  - local: mongo-writer/.gitlab-ci.yml
  - local: runtime-entrypoint/.gitlab-ci.yml
  - local: runtime-runners/kre-py/.gitlab-ci.yml
  - local: runtime-runners/kre-go/.gitlab-ci.yml
