// Code generated by MockGen. DO NOT EDIT.
// Source: logs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kai/engine/admin-api/domain/entity"
)

// MockLogsUsecase is a mock of LogsUsecase interface.
type MockLogsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLogsUsecaseMockRecorder
}

// MockLogsUsecaseMockRecorder is the mock recorder for MockLogsUsecase.
type MockLogsUsecaseMockRecorder struct {
	mock *MockLogsUsecase
}

// NewMockLogsUsecase creates a new mock instance.
func NewMockLogsUsecase(ctrl *gomock.Controller) *MockLogsUsecase {
	mock := &MockLogsUsecase{ctrl: ctrl}
	mock.recorder = &MockLogsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogsUsecase) EXPECT() *MockLogsUsecaseMockRecorder {
	return m.recorder
}

// GetLogs mocks base method.
func (m *MockLogsUsecase) GetLogs(logFilters entity.LogFilters) ([]*entity.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", logFilters)
	ret0, _ := ret[0].([]*entity.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockLogsUsecaseMockRecorder) GetLogs(logFilters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockLogsUsecase)(nil).GetLogs), logFilters)
}
