apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-manager.fullname" . }}
  labels:
    {{- include "kai.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  KRE_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KRE_RELEASE_NAME: "{{ .Release.Name }}"

  # NATS Streaming
  KRE_NATS_URL: "{{ include "nats.url" . }}"
