apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: proto.{{ .Values.entrypoint.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: web
