## datasources values reference: https://github.com/felipegutierrez/explore-flink/blob/master/k8s/grafana-configuration-configmap.yaml
## redis datasource reference: https://redisgrafana.github.io/redis-datasource/provisioning/
{{- if and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana-datasources.fullname" . }}
  labels:
    {{- include "grafana-datasources.labels" . | nindent 4 }}
    {{- if .Values.grafana.sidecar.datasources.label }}
    {{ .Values.grafana.sidecar.datasources.label }}: {{ .Values.grafana.sidecar.datasources.labelValue | quote }}
    {{- else }}
    grafana_datasource: "1"
    {{- end }}
data:
  grafana-datasources.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: {{ include "loki.url" . }}
      version: 1
      isDefault: {{ default false .Values.config.loki.isDefault }}
      {{- with .Values.config.loki.datasource.uid }}
      uid: {{ . | quote }}
      {{- end }}
      {{- with .Values.config.loki.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: {{ include "prometheus.url" . }}
      version: 1
      isDefault: {{ default false .Values.config.prometheus.isDefault }}
      {{- with .Values.config.prometheus.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.redis.enabled }}
    - name: Redis
      type: redis-datasource
      access: proxy
      url: redis://{{ include "redis.master.url" . }}
      version: 1
      isDefault: false
      jsonData:
        client: {{ .Values.redis.architecture }}
      {{- if .Values.redis.auth.enabled }}
      secureJsonData:
        password: {{ include "redis.auth.password" . }}
      {{- end }}
{{- end }}
{{- end }}
