apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-manager.fullname" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
data:
  KAI_API_LOG_LEVEL: {{ .Values.adminApi.logLevel }}
  KAI_KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
  KAI_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KAI_RELEASE_NAME: "{{ .Release.Name }}"
  KAI_BASE_DOMAIN_NAME: {{ .Values.config.baseDomainName }}
  KAI_TRIGGERS_REQUEST_TIMEOUT: "30"
  KAI_TRIGGERS_BASE64_INGRESSES_ANNOTATIONS: {{ .Values.k8sManager.processes.triggers.ingress.annotations | toYaml | b64enc }}
  KAI_TRIGGERS_TLS_ENABLED: "{{ .Values.config.tls.enabled }}"
  {{- if .Values.config.tls.enabled }}
  KAI_TRIGGERS_TLS_CERT_SECRET_NAME: {{ .Values.config.tls.certSecretName }}
  {{- end }}
  {{- if .Values.k8sManager.processes.triggers.ingress.className }}
  KAI_TRIGGERS_INGRESS_CLASS_NAME: {{ .Values.k8sManager.processes.triggers.ingress.className }}
  {{- end }}
  KAI_NATS_URL: "{{ include "nats.url" . }}"
  KAI_NATS_HOST: "{{ include "nats.host" . }}"
  KAI_REGISTRY_HOST: "{{ .Values.registry.host }}"
  KAI_REGISTRY_AUTH_SECRET_NAME: "{{ include "registry.auth.secretName" . }}"
  KAI_REGISTRY_INSECURE: "{{ not .Values.config.tls.enabled }}"
  KAI_MINIO_ENDPOINT_URL: "{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
  KAI_MINIO_REGION: {{ include "minio-config.region" . }}
  KAI_KEYCLOAK_BASE_URL: "http://{{ include "keycloak.fullname" . }}:{{ .Values.keycloak.service.ports.http }}"
  KAI_KEYCLOAK_REALM: "{{ .Values.keycloak.realmName }}"
  KAI_KEYCLOAK_MINIO_CLIENT_ID: "{{ .Values.keycloak.minio.oidcClient.clientId }}"
  KAI_FLUENTBIT_IMAGE_REPOSITORY: {{ .Values.k8sManager.processes.sidecars.fluentbit.image.repository }}
  KAI_FLUENTBIT_IMAGE_TAG: {{ .Values.k8sManager.processes.sidecars.fluentbit.image.tag }}
  KAI_FLUENTBIT_IMAGE_PULLPOLICY: {{ .Values.k8sManager.processes.sidecars.fluentbit.image.pullPolicy }}
  KAI_TELEGRAF_IMAGE_REPOSITORY: {{ .Values.k8sManager.processes.sidecars.telegraf.image.repository }}
  KAI_TELEGRAF_IMAGE_TAG: {{ .Values.k8sManager.processes.sidecars.telegraf.image.tag }}
  KAI_TELEGRAF_IMAGE_PULLPOLICY: {{ .Values.k8sManager.processes.sidecars.telegraf.image.pullPolicy }}
  KAI_LOKI_HOST: {{ include "loki.host" . }}
  KAI_LOKI_PORT: {{ include "loki.port" . }}
  KAI_IMAGE_BUILDER_IMAGE_REPOSITORY: {{ .Values.k8sManager.imageBuilder.image.repository }}
  KAI_IMAGE_BUILDER_IMAGE_TAG: {{ .Values.k8sManager.imageBuilder.image.tag }}
  KAI_IMAGE_BUILDER_IMAGE_PULLPOLICY: {{ .Values.k8sManager.imageBuilder.image.pullPolicy }}
  KAI_IMAGE_BUILDER_NETRC_ENABLED: {{ .Values.k8sManager.imageBuilder.netrc.enabled }}
  {{- if .Values.k8sManager.imageBuilder.netrc.enabled }}
  KAI_IMAGE_BUILDER_NETRC_SECRET_NAME: "{{ include "k8s-manager.netrc.secretName" . }}"
  {{- end }}
  KAI_REDIS_MASTER_ADDRESS: {{ include "redis.master.url" . }}
