apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-manager.fullname" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-manager.selectorLabels" . | nindent 6 }}
  {{- with .Values.k8sManager.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "k8s-manager.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/k8s-manager/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.k8sManager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-manager.serviceAccountName" . }}
      {{- with .Values.k8sManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.k8sManager.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.k8sManager.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "k8s-manager.fullname" . }}
          image: {{ .Values.k8sManager.image.repository }}:{{ .Values.k8sManager.image.tag }}
          imagePullPolicy: {{ .Values.k8sManager.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "k8s-manager.fullname" . }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAI_MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" .Subcharts.minio }}
                  key: rootUser
            - name: KAI_MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" .Subcharts.minio }}
                  key: rootPassword
            - name: KAI_KEYCLOAK_MINIO_CLIENT_SECRET
              value: "{{ .Values.keycloak.minio.oidcClient.secret }}"
            - name: KAI_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.auth.secretName" . }}
                  key: {{ include "redis.auth.secretPasswordKey" . }}
          ports:
            - containerPort: 50051
              protocol: TCP
              name: grpc
          resources:
            {{- toYaml .Values.k8sManager.resources | nindent 12 }}
