{{- if .Values.k8sManager.imageBuilder.netrc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-manager.netrc.secretName" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
type: kubernetes.io/netrcconfig
stringData:
  .netrcconfig: {{ toYaml .Values.k8sManager.imageBuilder.netrc.content | indent 2 }}
{{- end }}
