apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretName" . }}-realm-config
type: Opaque
stringData:
  realm.json: |-
    {
      "realm": "{{ .Values.keycloak.realmName }}",
      "enabled": true,
      "ssoSessionIdleTimeout": {{ .Values.keycloak.ssoSessionIdleTimeout }},
      "clients": [
        {
          "clientId" : "{{ .Values.keycloak.kong.oidcClient.clientId }}",
          "name" : "${client_{{ .Values.keycloak.kong.oidcClient.clientId }}}",
          "description" : "OIDC client for Kong ingresses",
          "rootUrl" : "",
          "adminUrl" : "",
          "baseUrl" : "",
          "surrogateAuthRequired" : false,
          "enabled" : true,
          "alwaysDisplayInConsole" : false,
          "clientAuthenticatorType" : "client-secret",
          "secret" : "{{ .Values.keycloak.kong.oidcClient.secret }}",
          "redirectUris" : [ "*" ],
          "bearerOnly" : false,
          "consentRequired" : false,
          "standardFlowEnabled" : true,
          "implicitFlowEnabled" : false,
          "directAccessGrantsEnabled" : true,
          "serviceAccountsEnabled" : false,
          "publicClient" : false,
          "frontchannelLogout" : true,
          "protocol" : "openid-connect",
          "attributes" : {
            "oidc.ciba.grant.enabled" : "false",
            "backchannel.logout.session.required" : "true",
            "post.logout.redirect.uris" : "*",
            "oauth2.device.authorization.grant.enabled" : "false",
            "backchannel.logout.revoke.offline.tokens" : "false"
          },
          "authenticationFlowBindingOverrides" : { },
          "fullScopeAllowed" : true,
          "nodeReRegistrationTimeout" : -1,
          "defaultClientScopes" : [ "web-origins", "acr", "profile", "roles", "email" ],
          "optionalClientScopes" : [ "address", "phone", "offline_access", "microprofile-jwt" ],
          "access" : {
            "view" : true,
            "configure" : true,
            "manage" : true
          }
        },
        {
          "clientId": "{{ .Values.keycloak.kli.oidcClient.clientId }}",
          "name": "${client_{{ .Values.keycloak.kli.oidcClient.clientId }}}",
          "description": "OIDC client for KLI",
          "rootUrl": "",
          "adminUrl": "",
          "baseUrl": "",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": false,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ],
          "notBefore": 0,
          "bearerOnly": false,
          "consentRequired": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "post.logout.redirect.uris": "*",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "authenticationFlowBindingOverrides": {},
          "fullScopeAllowed": true,
          "nodeReRegistrationTimeout": -1,
          "protocolMappers": [
            {
              "name": "KAI Product Roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-attribute-mapper",
              "consentRequired": false,
              "config": {
                "aggregate.attrs": "true",
                "userinfo.token.claim": "false",
                "multivalued": "false",
                "user.attribute": "product_roles",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "product_roles",
                "jsonType.label": "JSON"
              }
            }
          ],
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        },
        {
          "clientId": "{{ .Values.keycloak.minio.oidcClient.clientId }}",
          "name": "${client_{{ .Values.keycloak.minio.oidcClient.clientId }}}",
          "description": "OIDC client for MinIO",
          "rootUrl": "${authBaseUrl}",
          "adminUrl": "${authBaseUrl}",
          "baseUrl": "/realms/konstellation/account/",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ .Values.keycloak.minio.oidcClient.secret }}",
          "redirectUris": [
            "*"
          ],
          "webOrigins": [],
          "notBefore": 0,
          "bearerOnly": false,
          "consentRequired": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "publicClient": false,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "access.token.lifespan": "3600",
            "oauth2.device.authorization.grant.enabled": "false",
            "use.jwks.url": "true",
          "backchannel.logout.revoke.offline.tokens": "false",
          "use.refresh.tokens": "true",
            "oidc.ciba.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "client_credentials.use_refresh_token": "false",
            "acr.loa.map": "{}",
            "require.pushed.authorization.requests": "false",
            "tls.client.certificate.bound.access.tokens": "false",
            "display.on.consent.screen": "false",
            "token.response.type.bearer.lower-case": "false"
          },
          "authenticationFlowBindingOverrides": {},
          "fullScopeAllowed": true,
          "nodeReRegistrationTimeout": -1,
          "protocolMappers": [
            {
              "name": "Client ID",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usersessionmodel-note-mapper",
              "consentRequired": false,
              "config": {
                "user.session.note": "client_id",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "client_id",
                "jsonType.label": "String"
              }
            },
            {
              "name": "Client IP Address",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usersessionmodel-note-mapper",
              "consentRequired": false,
              "config": {
                "user.session.note": "clientAddress",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "clientAddress",
                "jsonType.label": "String"
              }
            },
            {
              "name": "Client Host",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usersessionmodel-note-mapper",
              "consentRequired": false,
              "config": {
                "user.session.note": "clientHost",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "clientHost",
                "jsonType.label": "String"
              }
            },
            {
              "name": "Minio Groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "config": {
                "claim.name": "groups",
                "full.path": false,
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": false
              }
            }
          ],
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        },
        {
          "clientId": "{{ .Values.keycloak.kliCI.oidcClient.clientId}}",
          "name": "${client_{{ .Values.keycloak.kliCI.oidcClient.clientId }}}",
          "description": "OIDC client for KLI in CI mode",
          "rootUrl": "",
          "adminUrl": "",
          "baseUrl": "",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": false,
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ .Values.keycloak.kliCI.oidcClient.secret }}",
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ],
          "notBefore": 0,
          "bearerOnly": false,
          "consentRequired": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "publicClient": false,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "post.logout.redirect.uris": "*",
            "oauth2.device.authorization.grant.enabled": "false",
            "display.on.consent.screen": "false",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "authenticationFlowBindingOverrides": {},
          "fullScopeAllowed": true,
          "nodeReRegistrationTimeout": -1,
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "roles",
            "profile",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        }
      ],
      "groups": [
        {
          "name": "admins",
          "path": "/admins",
          "attributes": {},
          "realmRoles": [
            "ADMIN"
          ],
          "clientRoles": {},
          "subGroups": []
        },
        {
          "name": "users",
          "path": "/users",
          "attributes": {},
          "realmRoles": [
            "USER"
          ],
          "clientRoles": {},
          "subGroups": []
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "ADMIN",
            "description": "${role_ADMIN}",
            "composite": false,
            "clientRole": false,
            "attributes": {}
          },
          {
            "name": "USER",
            "description": "${role_USER}",
            "composite": false,
            "clientRole": false,
            "attributes": {}
          }
        ]
      }
    }
