{{- if not .Values.keycloak.auth.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.secretName" . }}
type: Opaque
data:
  admin-user: {{ .Values.keycloak.auth.adminUser | b64enc }}
  admin-password: {{ default (randAlphaNum 16) .Values.keycloak.auth.adminPassword | b64enc }}
  {{- if not .Values.keycloak.db.auth.secretName }}
  database-user: {{ .Values.keycloak.db.auth.password | b64enc }}
  database-password: {{ .Values.keycloak.db.auth.username | b64enc }}
  {{- end }}
{{- end }}
