apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kre.fullname" . }}-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kre.labels" . | nindent 6 }}
      app: {{ template "kre.fullname" . }}-admin-ui
  template:
    metadata:
      labels:
        {{- include "kre.labels" . | nindent 8 }}
        app: {{ template "kre.fullname" . }}-admin-ui
        type: admin
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ template "kre.fullname" . }}-admin-ui
          image: {{ .Values.adminUI.image.repository }}:{{ .Values.adminUI.image.tag }}
          imagePullPolicy: {{ .Values.adminUI.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config/config.json
              subPath: config.json
          ports:
            - containerPort: {{ .Values.adminUI.service.port }}
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-admin-ui-configmap
