apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kre.fullname" . }}-admin-ui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ template "kre.fullname" . }}-admin-ui
    certmanager.k8s.io/acme-challenge-type: http01
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app:  {{ template "kre.fullname" . }}-admin-ui-ingress
spec:
  {{- if .Values.adminUI.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.adminUI.host }}
    secretName: {{ .Values.adminUI.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminUI.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-ui
              servicePort: {{ .Values.adminUI.service.port }}
