apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- if .Values.keycloak.tls }}
  tls:
    - hosts:
        - {{ .Values.keycloak.host }}
      secretName: {{ .Values.keycloak.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.host }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "keycloak.fullname" .}}
                port:
                  {{- if .Values.keycloak.config.httpEnabled }}
                  name: http
                  {{- else }}
                  name: https
                  {{- end }}
              {{- else }}
              serviceName: {{ include "keycloak.fullname" .}}
              servicePort: http
              {{- end }}
  