{{- if .Values.keycloak.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.keycloak.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
