entrypoint:
  host: "local"

nats_streaming:
  replicas: 2
  storage:
    className: standard
    size: 1Gi

mongo:
  replicas: 1
  credentials:
    username: admin
    password: "123456"
  storage:
    className: standard
    size: 1Gi

minio:
  credentials:
    accessKey: admin
    secretKey: "12345678"
  storage:
    className: standard
    size: 1Gi
