apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongo-writer.fullname" . }}
  labels:
    {{- include "mongo-writer.labels" . | nindent 4 }}
data:
  KRE_NATS_URL: "{{ include "nats.url" . }}"
  KRE_PORT: "50051"
