{{- if or .Values.prometheus.enabled .Values.config.prometheus.kaiScrapeConfigs.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.prometheus.kaiScrapeConfigs.configmapName }}
  labels:
    {{- include "prometheus-additional-scrape-configs.labels" . | nindent 4 }}
data:
  kai-scrape-config.yaml: |
    scrape_configs:
    - job_name: kai-processes-pods
      scrape_interval: 1s
      scrape_timeout: 1s
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_kai_prometheus_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_kai_prometheus_scheme]
          action: replace
          target_label: __scheme__
          regex: (http?)
        - source_labels: [__meta_kubernetes_pod_annotation_kai_prometheus_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_kai_prometheus_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_service
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod
  {{- end }}
