baseDomainName: "local"
releaseName: ""
releaseVersion: "latest"
application:
  versionStatusTimeout: 20m
admin:
  apiAddress: ":4000"
  baseURL: "http://api.kai.local"
  corsEnabled: true
mongodb:
  endpoint: "mongodb://admin:123456@localhost:27017/admin?replicaSet=rs0"
  dbName: "kai"
  krtBucket: "krt"
services:
  k8sManager: "localhost:50051"
  natsManager: "localhost:50052"
