apiVersion: v2
appVersion: "0.2.0-develop.62"
description: KAI
name: kai
version: 0.2.0-develop.62
dependencies:
  - name: influxdb
    version: "4.8.1"
    repository: https://helm.influxdata.com/
  - name: kapacitor
    version: "1.4.6"
    repository: https://helm.influxdata.com/
    condition: kapacitor.enabled
  - name: minio
    version: "5.0.14"
    repository: https://charts.min.io/
  - name: grafana
    version: "7.0.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    repository: "https://grafana.github.io/helm-charts"
    version: "5.36.3"
    condition: loki.enabled
  - name: prometheus
    version: "25.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: redis
    version: "18.2.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
