apiVersion: v2
appVersion: "0.1.1-develop.1"
description: KAI
name: kai
version: 0.1.1-develop.1
dependencies:
  - name: influxdb
    version: "4.8.1"
    repository: https://helm.influxdata.com/
  - name: kapacitor
    version: "1.4.6"
    repository: https://helm.influxdata.com/
    condition: kapacitor.enabled
