apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-runtime-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-runtime-operator
  template:
    metadata:
      labels:
        name: k8s-runtime-operator
    spec:
      serviceAccountName: k8s-runtime-operator
      containers:
        - name: k8s-runtime-operator
          # Replace this with the built image name
          image: k8s-runtime-operator:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-runtime-operator"
