plugins:

  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig

  duplication:
    enabled: true
    config:
      languages:
        - go:

  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO

  gofmt:
    enabled: true

  govet:
    enabled: true

  golint:
    enabled: true

exclude_patterns:
  # this patterns are a hack to try and run only for admin-api and have proper links on Gitlab MR page
  - "**/*"
  - "!admin-api/**"
  - "**/*.pb.go"
  - "**/mocks/"
