{{- $protocol := ternary  "https" "http" .Values.adminApi.tls.enabled -}}
{{- $keycloak_protocol := ternary "https" "http" .Values.keycloak.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KAI_API_LOG_LEVEL: "{{ .Values.adminApi.logLevel }}"
  KAI_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KAI_RELEASE_NAME: "{{ .Release.Name }}"
  KAI_ADMIN_API_BASE_URL: "{{ $protocol }}://{{ .Values.config.admin.apiHost }}"
  KAI_ADMIN_CORS_ENABLED: "{{ .Values.config.admin.corsEnabled }}"
  KAI_SERVICES_K8S_MANAGER: "{{ include "k8s-manager.fullname" . }}:50051"
  KAI_SERVICES_NATS_MANAGER: "{{ include "nats-manager.fullname" . }}:50051"
  KAI_MONGODB_MONGOEXPRESS_ADDRESS: http://{{ include "mongoExpress.fullname" . }}
  KAI_BASE_DOMAIN_NAME: "{{ .Values.config.baseDomainName }}"
  KAI_ADMIN_STORAGE_PATH: "{{ .Values.adminApi.storage.path }}"
  KAI_ADMIN_API_ADDRESS: ":8080"
  # InfluxDB
  KAI_INFLUXDB_ADDRESS: "{{ include "kai-influxdb.influxURL" . }}"
  # Chronograf
  KAI_CHRONOGRAF_ADDRESS: "http://{{ include "chronograf.fullname" . }}"
  # Keycloak
  KEYCLOAK_BASE_URL: "http://{{ include "keycloak.fullname" . }}:{{ .Values.keycloak.service.ports.http }}"
  KEYCLOAK_MASTER_REALM: "master"
  KEYCLOAK_REALM: "{{ .Values.keycloak.realmName }}"
  KEYCLOAK_ADMIN_CLIENT_ID: "{{ .Values.keycloak.adminApi.oidcClient.clientId }}"
  # REGISTRY
  KAI_REGISTRY_HOST: "{{ .Values.registry.host }}"
  # S3
  KAI_MINIO_ENDPOINT_URL: "{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
  AWS_REGION: "{{ include "admin-api.s3.region" . }}"
