{{- $protocol := ternary  "https" "http" .Values.adminApi.tls.enabled -}}
{{- $keycloak_protocol := ternary "https" "http" .Values.keycloak.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KRE_API_LOG_LEVEL: {{ .Values.adminApi.logLevel }}
  KRE_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KRE_RELEASE_NAME: "{{ .Release.Name }}"
  KRE_ADMIN_API_BASE_URL: "{{ $protocol }}://{{ .Values.config.admin.apiHost }}"
  KRE_ADMIN_CORS_ENABLED: "{{ .Values.config.admin.corsEnabled }}"
  KRE_SERVICES_K8S_MANAGER: "{{ include "k8s-manager.fullname" . }}:50051"
  KRE_SERVICES_NATS_MANAGER: "{{ include "nats-manager.fullname" . }}:50051"
  KRE_MONGODB_MONGOEXPRESS_ADDRESS: http://{{ include "mongoExpress.fullname" . }}
  KRE_BASE_DOMAIN_NAME: {{ .Values.config.baseDomainName }}
  KRE_ADMIN_STORAGE_PATH: {{ .Values.adminApi.storage.path }}
  KRE_ADMIN_API_ADDRESS: ":8080"
  # InfluxDB
  KRE_INFLUXDB_ADDRESS: {{ include "kai-influxdb.influxURL" . }}
  # Chronograf
  KRE_CHRONOGRAF_ADDRESS: http://{{ include "chronograf.fullname" . }}
  # Keycloak
  KEYCLOAK_BASE_URL: "http://{{ include "keycloak.fullname" . }}:{{ .Values.keycloak.service.ports.http }}"
  KEYCLOAK_MASTER_REALM: "master"
  KEYCLOAK_REALM: "{{ .Values.keycloak.realmName }}"
  KEYCLOAK_ADMIN_CLIENT_ID: "{{ .Values.keycloak.adminApi.oidcClient.clientId }}"
