apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "admin-api.fullname" . }}
  annotations:
    konghq.com/plugins: {{ include "kai.fullname" . }}-oidc
    konghq.com/strip-path: "false"
    {{- with .Values.adminApi.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.adminApi.ingress.className }}
  ingressClassName: {{ .Values.adminApi.ingress.className }}
  {{- end }}
  {{- if .Values.adminApi.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminApi.host }}
      secretName: {{ .Values.adminApi.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.host }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "admin-api.fullname" . }}
                port:
                  name: grpc
              {{- else }}
              serviceName: {{ include "admin-api.fullname" . }}
              servicePort: grpc
              {{- end }}
