# Job to configure a MinIO Tier (transition objects to external extorage)
{{- if and .Values.config.minio.tier.enabled }}
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "minio-config.fullname" . }}
  labels:
    {{- include "minio-config.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "minio-config.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: minio-client-config
          image: minio/mc
          env:
            # Set tier provider
            {{- if or (and .Values.config.minio.tier.aws.auth.secretName .Values.config.minio.tier.aws.auth.secretKeyNames.accessKey .Values.config.minio.tier.aws.auth.secretKeyNames.secretKey) (and .Values.config.minio.tier.aws.auth.accessKeyID .Values.config.minio.tier.aws.auth.secretAccessKey) }}
            - name: TIER_SELECTED
              value: "aws"
            {{- end }}

            # MINIO config
            - name: KAI_MINIO_ENDPOINT_URL
              value: "http://{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
            - name: REMOTE_BUCKET_NAME
              value: {{ .Values.config.minio.tier.remoteBucketName }}
            ## tier.name (set in values / default)
            {{- if .Values.config.minio.tier.name }}
            - name: TIER_NAME
              value: {{ .Values.config.minio.tier.name }}
            {{- else }}
            - name: TIER_NAME
              value: {{ include "minio-config.tier.name" . }}
            {{- end }}
            ## remotePrefix (set in values / default)
            {{- if .Values.config.minio.tier.aws.remotePrefix }}
            - name: REMOTE_PREFIX
              value: {{ .Values.config.minio.tier.remotePrefix }}
            {{- else }}
            - name: REMOTE_PREFIX
              value: {{ include "minio-config.tier.s3.remotePrefix" . }}
            {{- end }}
            ## values from minio subchart
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" .Subcharts.minio }}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secretName" .Subcharts.minio }}
                  key: rootPassword

            # AWS config
            ## in case of existing secret keys
            {{- if .Values.config.minio.tier.aws.auth.secretName }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.minio.tier.aws.auth.secretName }}
                  key: {{ .Values.config.minio.tier.aws.auth.secretKeyNames.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.minio.tier.aws.auth.secretName }}
                  key: {{ .Values.config.minio.tier.aws.auth.secretKeyNames.secretKey }}
            ## in case of set keys in values.yaml
            {{- else }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.config.minio.tier.aws.auth.accessKeyID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.config.minio.tier.aws.auth.secretAccessKey }}
            {{- end }}
            ## endpointURL (set in values / default)
            {{- if .Values.config.minio.tier.aws.endpointURL }}
            - name: AWS_ENDPOINT_URL_S3
              value: {{ .Values.config.minio.tier.aws.endpointURL }}
            {{- else }}
            - name: AWS_ENDPOINT_URL_S3
              value: {{ include "minio-config.tier.s3.endpointURL" . }}
            {{- end }}
            ## region (set in values / default)
            {{- if .Values.config.minio.tier.aws.region }}
            - name: AWS_REGION
              value: {{ .Values.config.minio.tier.aws.region }}
            {{- else }}
            - name: AWS_REGION
              value: {{ include "minio-config.tier.s3.region" . }}
            {{- end }}

          command: ["/bin/bash", "-c"]
          args:
            - |
              echo -e "Checking MinIO \`/health/live\` endpoint until get 200 code..."
              until [ "$(curl -s -w '%{http_code}' -o /dev/null "${KAI_MINIO_ENDPOINT_URL}/minio/health/live")" -eq 200 ]; do sleep 2; done
              echo -e "200 Ok \nMinIO is UP and Running, configuring MinIO client (mc) against MinIO server"
              mc alias set kai-minio $KAI_MINIO_ENDPOINT_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              if [ "$TIER_SELECTED" == "aws" ]; then
                echo -e "Tier provider selected: [AWS S3] \nChecking required variables for this tier"
                variables=("TIER_NAME" "AWS_ENDPOINT_URL_S3" "AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "REMOTE_BUCKET_NAME" "REMOTE_PREFIX" "AWS_REGION")
                for var in "${variables[@]}"; do
                  if [ -z "${!var}" ]; then
                    echo "ERROR: The variable $var is undefined or empty."
                    exit 1
                  fi
                done
                echo "All required variables are defined, creating the MinIO tier"
                mc ilm tier add s3 kai-minio $TIER_NAME --endpoint $AWS_ENDPOINT_URL_S3 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --bucket $REMOTE_BUCKET_NAME --prefix $REMOTE_PREFIX --region $AWS_REGION --force
                echo "Job completed successfully!"
              else
                echo "Minio Tier was enabled, but no specific configuration has been found for any Tier. Please check '.Values.config.minio.tier' section"
                exit 1
              fi
{{- end }}
