apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KAI_AUTH_JWT_SIGN_SECRET: {{ .Values.config.auth.jwtSignSecret | b64enc }}
  KAI_AUTH_API_TOKEN_SECRET: "{{ .Values.config.auth.apiTokenSecret | b64enc }}"
