apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-manager.fullname" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
data:
  KAI_API_LOG_LEVEL: {{ .Values.adminApi.logLevel }}
  KAI_KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
  KAI_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KAI_RELEASE_NAME: "{{ .Release.Name }}"
  KAI_BASE_DOMAIN_NAME: {{ .Values.config.baseDomainName }}
  KAI_ENTRYPOINTS_REQUEST_TIMEOUT: "30"
  KAI_ENTRYPOINTS_BASE64_INGRESSES_ANNOTATIONS: {{ .Values.k8sManager.generatedEntrypoints.ingress.annotations | toYaml | b64enc }}
  KAI_ENTRYPOINTS_TLS: "{{ .Values.k8sManager.generatedEntrypoints.tls }}"
    {{- if and .Values.k8sManager.generatedEntrypoints.tls .Values.k8sManager.generatedEntrypoints.ingress.tls.secretName }}
  KAI_ENTRYPOINTS_TLS_CERT_SECRET_NAME: {{ .Values.k8sManager.generatedEntrypoints.ingress.tls.secretName }}
  {{- end }}
  {{- if .Values.k8sManager.generatedEntrypoints.ingress.className }}
  KAI_ENTRYPOINTS_INGRESS_CLASS_NAME: {{ .Values.k8sManager.generatedEntrypoints.ingress.className }}
  {{- end }}
  KAI_NATS_URL: "{{ include "nats.url" . }}"
  KAI_NATS_HOST: "{{ include "nats.host" . }}"
  KAI_REGISTRY_HOST: "{{ .Values.registry.host }}"
  KAI_REGISTRY_AUTH_SECRET_NAME: "{{ include "registry.auth.secretName" . }}"
  KAI_REGISTRY_INSECURE: "{{ not .Values.registry.tls.enabled }}"
