apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-manager.fullname" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
data:
  KAI_API_LOG_LEVEL: {{ .Values.adminApi.logLevel }}
  KAI_KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
  KAI_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KAI_RELEASE_NAME: "{{ .Release.Name }}"
  KAI_BASE_DOMAIN_NAME: {{ .Values.config.baseDomainName }}
  KAI_TRIGGERS_REQUEST_TIMEOUT: "30"
  KAI_TRIGGERS_BASE64_INGRESSES_ANNOTATIONS: {{ .Values.k8sManager.triggers.ingress.annotations | toYaml | b64enc }}
  KAI_TRIGGERS_TLS_ENABLED: "{{ .Values.config.tls }}"
  {{- if .Values.config.tls }}
  KAI_TRIGGERS_TLS_CERT_SECRET_NAME: {{ .Values.config.tls.certSecretName }}
  {{- end }}
  {{- if .Values.k8sManager.triggers.ingress.className }}
  KAI_TRIGGERS_INGRESS_CLASS_NAME: {{ .Values.k8sManager.triggers.ingress.className }}
  {{- end }}
  KAI_NATS_URL: "{{ include "nats.url" . }}"
  KAI_NATS_HOST: "{{ include "nats.host" . }}"
  KAI_REGISTRY_HOST: "{{ .Values.registry.host }}"
  KAI_REGISTRY_AUTH_SECRET_NAME: "{{ include "registry.auth.secretName" . }}"
  KAI_REGISTRY_INSECURE: "{{ not .Values.config.tls.enabled }}"
  KAI_MINIO_ENDPOINT_URL: "{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
