{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-manager.fullname" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-manager.serviceAccountName" . }}
    apiGroup: ""
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "k8s-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
