apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kre.fullname" . }}-admin-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "kre.labels" . | nindent 8 }}
        app: {{ .Chart.Name }}-admin-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-admin-api
          image: {{ .Values.adminApi.image.repository }}:{{ .Values.adminApi.image.tag }}
          imagePullPolicy: {{ .Values.adminApi.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-secrets

          ports:
            - containerPort: {{ .Values.adminApi.service.port }}
              protocol: TCP
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets  }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

