apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kre.fullname" . }}-admin-api-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ template "kre.fullname" . }}-admin-api
    certmanager.k8s.io/acme-challenge-type: http01
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app:  {{ template "kre.fullname" . }}-admin-api-ingress
spec:
  {{- if .Values.adminApi.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.adminApi.tls.host }}
    secretName: {{ .Values.adminApi.tls.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.tls.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-api
              servicePort: {{ .Values.adminApi.service.port }}
