apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-manager
subjects:
- kind: ServiceAccount
  name: k8s-manager
  apiGroup: ""
  namespace: kre
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
