apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runtimes.kre.konstellation.io
spec:
  group: kre.konstellation.io
  names:
    kind: Runtime
    listKind: RuntimeList
    plural: runtimes
    singular: runtime
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
