## based on this docs: https://medium.com/@gerkElznik/deploy-redis-stack-using-bitnamis-helm-chart-d8339453352c
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-stack-master-config
  labels:
    {{- include "prometheus-additional-scrape-configs.labels" . | nindent 4 }}
data:
  start-master.sh: |
    #!/usr/bin/dumb-init /bin/bash
    ### docker entrypoint script, for starting redis stack
    export BASEDIR=/opt/redis-stack
    cd ${BASEDIR}
    export CMD=${BASEDIR}/bin/redis-server
    if [ -z "${REDISEARCH_ARGS}" ]; then
    export REDISEARCH_ARGS="MAXSEARCHRESULTS 10000 MAXAGGREGATERESULTS 10000"
    fi
    if [ -z "${REDISGRAPH_ARGS}" ]; then
    export REDISGRAPH_ARGS="MAX_QUEUED_QUERIES 25 TIMEOUT 1000 RESULTSET_SIZE 10000"
    fi
    [[ -f $REDIS_PASSWORD_FILE ]] && export REDIS_PASSWORD="$(< "${REDIS_PASSWORD_FILE}")"
    if [[ -f /opt/bitnami/redis/mounted-etc/master.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/master.conf /opt/bitnami/redis/etc/master.conf
    fi
    if [[ -f /opt/bitnami/redis/mounted-etc/redis.conf ]];then
        cp /opt/bitnami/redis/mounted-etc/redis.conf /opt/bitnami/redis/etc/redis.conf
    fi
    ${CMD} \
    --port "${REDIS_PORT}" \
    --requirepass "${REDIS_PASSWORD}" \
    --masterauth "${REDIS_PASSWORD}" \
    --include "/opt/bitnami/redis/etc/redis.conf" \
    --include "/opt/bitnami/redis/etc/master.conf" \
    --loadmodule /opt/redis-stack/lib/redisearch.so ${REDISEARCH_ARGS} \
    --loadmodule /opt/redis-stack/lib/redistimeseries.so ${REDISTIMESERIES_ARGS} \
    --loadmodule /opt/redis-stack/lib/rejson.so ${REDISJSON_ARGS} \
    --loadmodule /opt/redis-stack/lib/redisbloom.so ${REDISBLOOM_ARGS}
{{- end }}
