apiVersion: v2
appVersion: "0.1"
description: Konstellation Runtime Environment Chart
name: kre
version: 0.1.7
dependencies:
  - name: mongodb
    version: "7.4.5"
    repository: "https://kubernetes-charts.storage.googleapis.com"
  - name: prometheus-operator
    version: "9.1.1"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    condition: prometheusOperator.enabled
