plugins:

  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig

  duplication:
    enabled: true
    config:
      languages:
        - go:
        - javascript:
        - typescript:

  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO

  gofmt:
    enabled: true

  govet:
    enabled: true

  golint:
    enabled: true

exclude_patterns:
  # this patterns are a hack to try and run only for runtime-api and have proper links on Gitlab MR page
  - "**"
  - "!runtime-api/**"
  - "**/*.pb.go"
  - mocks/
  - "**/mocks/"
