release-runtime-api:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix runtime-api
  script:
    - cd runtime-api && npx semantic-release -e semantic-release-monorepo
  only:
    refs:
      - master
    changes:
      - runtime-api/**/*
      - .gitlab-ci.yml

publish-runtime-api-image:
  stage: publish-image
  image: docker:18-git
  services:
    - docker:18-dind
  variables:
    IMAGE_PROJECT_NAME: "konstellation/kre-runtime-api"
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - TAG=${CI_COMMIT_TAG#runtime-api-v}
    - docker build -t $IMAGE_PROJECT_NAME:$TAG runtime-api
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest

  only:
    refs:
      - /^runtime-api-v\d*.\d*.\d*$/
