apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{ include "kre.labels" . | nindent 4 }}
    app: {{ .Chart.Name }}-api
spec:
  clusterIP: None
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    {{ include "kre.labels" . | nindent 4 }}
    app: {{ .Chart.Name }}-api
