// Code generated by MockGen. DO NOT EDIT.
// Source: nats_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	regexp "regexp"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kai/engine/nats-manager/internal/entity"
)

// MockNatsClient is a mock of NatsClient interface.
type MockNatsClient struct {
	ctrl     *gomock.Controller
	recorder *MockNatsClientMockRecorder
}

// MockNatsClientMockRecorder is the mock recorder for MockNatsClient.
type MockNatsClientMockRecorder struct {
	mock *MockNatsClient
}

// NewMockNatsClient creates a new mock instance.
func NewMockNatsClient(ctrl *gomock.Controller) *MockNatsClient {
	mock := &MockNatsClient{ctrl: ctrl}
	mock.recorder = &MockNatsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsClient) EXPECT() *MockNatsClientMockRecorder {
	return m.recorder
}

// CreateKeyValueStore mocks base method.
func (m *MockNatsClient) CreateKeyValueStore(keyValueStore string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyValueStore", keyValueStore)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKeyValueStore indicates an expected call of CreateKeyValueStore.
func (mr *MockNatsClientMockRecorder) CreateKeyValueStore(keyValueStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyValueStore", reflect.TypeOf((*MockNatsClient)(nil).CreateKeyValueStore), keyValueStore)
}

// CreateObjectStore mocks base method.
func (m *MockNatsClient) CreateObjectStore(objectStore string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStore", objectStore)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateObjectStore indicates an expected call of CreateObjectStore.
func (mr *MockNatsClientMockRecorder) CreateObjectStore(objectStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStore", reflect.TypeOf((*MockNatsClient)(nil).CreateObjectStore), objectStore)
}

// CreateStream mocks base method.
func (m *MockNatsClient) CreateStream(streamConfig *entity.StreamConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStream", streamConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStream indicates an expected call of CreateStream.
func (mr *MockNatsClientMockRecorder) CreateStream(streamConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStream", reflect.TypeOf((*MockNatsClient)(nil).CreateStream), streamConfig)
}

// DeleteKeyValueStore mocks base method.
func (m *MockNatsClient) DeleteKeyValueStore(keyValueStore string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyValueStore", keyValueStore)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyValueStore indicates an expected call of DeleteKeyValueStore.
func (mr *MockNatsClientMockRecorder) DeleteKeyValueStore(keyValueStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyValueStore", reflect.TypeOf((*MockNatsClient)(nil).DeleteKeyValueStore), keyValueStore)
}

// DeleteObjectStore mocks base method.
func (m *MockNatsClient) DeleteObjectStore(stream string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStore", stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStore indicates an expected call of DeleteObjectStore.
func (mr *MockNatsClientMockRecorder) DeleteObjectStore(stream interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStore", reflect.TypeOf((*MockNatsClient)(nil).DeleteObjectStore), stream)
}

// DeleteStream mocks base method.
func (m *MockNatsClient) DeleteStream(stream string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStream", stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockNatsClientMockRecorder) DeleteStream(stream interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockNatsClient)(nil).DeleteStream), stream)
}

// GetObjectStoreNames mocks base method.
func (m *MockNatsClient) GetObjectStoreNames(optFilter ...*regexp.Regexp) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range optFilter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObjectStoreNames", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStoreNames indicates an expected call of GetObjectStoreNames.
func (mr *MockNatsClientMockRecorder) GetObjectStoreNames(optFilter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStoreNames", reflect.TypeOf((*MockNatsClient)(nil).GetObjectStoreNames), optFilter...)
}

// GetStreamNames mocks base method.
func (m *MockNatsClient) GetStreamNames(optFilter ...*regexp.Regexp) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range optFilter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStreamNames", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamNames indicates an expected call of GetStreamNames.
func (mr *MockNatsClientMockRecorder) GetStreamNames(optFilter ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamNames", reflect.TypeOf((*MockNatsClient)(nil).GetStreamNames), optFilter...)
}

// UpdateConfiguration mocks base method.
func (m *MockNatsClient) UpdateConfiguration(keyValueStore string, keyValueConfig map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfiguration", keyValueStore, keyValueConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfiguration indicates an expected call of UpdateConfiguration.
func (mr *MockNatsClientMockRecorder) UpdateConfiguration(keyValueStore, keyValueConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfiguration", reflect.TypeOf((*MockNatsClient)(nil).UpdateConfiguration), keyValueStore, keyValueConfig)
}
