test-admin-ui:
  stage: test
  image: node:14
  before_script:
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - apt update && apt install yarn -y
    - cd admin/admin-ui
    - yarn install
  script:
    - yarn run test:cov:ci
    - yarn run test:cov:sonar
  coverage: '/Statements   : \d+\.\d+/'
  artifacts:
    paths:
      - admin/admin-ui/test-report.xml
    reports:
      junit: admin/admin-ui/junit.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

sonar-admin-ui:
  extends: .sonar-scanner
  variables:
    SONAR_TOKEN: $SONAR_TOKEN_ADMIN_UI
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/admin/admin-ui/.sonar'
    COMPONENT_PATH: admin/admin-ui
    GIT_DEPTH: '0'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

release-admin-ui:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix admin/admin-ui
  script:
    - cd admin/admin-ui && npx semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - admin/admin-ui/**/*

publish-admin-ui-image:
  stage: publish-image
  image: docker:19
  services:
    - name: docker:19.03.6-dind
      command: ["--experimental"]

  variables:
    IMAGE_PROJECT_NAME: 'konstellation/kre-admin-ui'
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    BUILDX_BUILDER: multiarch
    BUILDX_PLATFORM: "linux/amd64,linux/arm64"

  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container --name ${BUILDX_BUILDER} --platform=${BUILDX_PLATFORM}
    - docker buildx inspect --bootstrap ${BUILDX_BUILDER}
    - docker buildx ls
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    # Generate statics
    - docker run --rm -v `pwd`/admin/admin-ui/:/app -w /app node:14 sh -c 'yarn install && yarn run build'
    - TAG=${CI_COMMIT_TAG#admin-ui-v}
    - docker buildx build --push --platform ${BUILDX_PLATFORM}
      --tag $IMAGE_PROJECT_NAME:$TAG
      --tag $IMAGE_PROJECT_NAME:latest
      admin/admin-ui
  rules:
    - if: '$CI_COMMIT_TAG =~ /^admin-ui-v\d*.\d*.\d*$/'
      when: always
