{{- if not .Values.registry.configSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{ include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.registry.config }}
  config.yml: |
    {{ .Values.registry.config | nindent 4 }}
  {{- else }}
  config.yml: |
    version: 0.1
    log:
      level: info
      formatter: text
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      {{- if .Values.registry.storageDriver.filesystem.enabled }}
      filesystem:
        rootdirectory: {{ .Values.registry.storage.path }}
      {{- else if .Values.registry.storageDriver.s3.enabled }}
      s3: {{ toYaml .Values.registry.storageDriver.s3.config | nindent 8 }}
      {{- end }}
    http:
      addr: :{{ .Values.registry.containerPort }}
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    auth:
      htpasswd:
        realm: konstellation
        path: /etc/docker/registry/htpasswd
  {{- end }}
{{- end }}
