apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-htpasswd
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd (include "registry.auth.user" . ) (include "registry.auth.password" . ) | b64enc }}
