apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.netrc.secretName" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: kubernetes.io/netrcconfig
stringData:
  .netrcconfig: "machine {{ include "registry.netrc.repository" . }} login {{ include "registry.netrc.user" . }} password {{ include "registry.netrc.token" . }}"
