apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.basicAuth.secretName" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  basic-auth: "{{ include "registry.auth.user" . }}:{{ include "registry.auth.password" . }}"
