{{- $auth := (printf "%s:%s" (include "registry.auth.user" . ) (include "registry.auth.password" . )) | b64enc -}}
{{- $protocol := ternary  "https" "http" .Values.config.tls.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.basicAuth.secretName" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "registry.basicAuth.secretKey" . }}: "{{ $auth }}"
