{{- $auth := (printf "%s:%s" (include "registry.auth.user" . ) (include "registry.auth.password" . )) | b64enc -}}
{{- $protocol := ternary  "https" "http" .Values.config.tls.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.auth.secretName" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "{\"auths\":{\"{{ $protocol }}://{{ .Values.registry.host }}\":{\"username\":\"{{ include "registry.auth.user" . }}\",\"password\":\"{{ include "registry.auth.password" . }}\",\"auth\":\"{{ $auth }}\"}}}"
