# Default values for konstellation.

adminApi:
  image:
    repository: konstellation/kre-admin-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3000
  tls:
    enabled: false
    host: admin-api-kre.local
