apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    {{- include "admin-api.labels"  . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.adminApi.storage.size }}
  storageClassName: {{ .Values.adminApi.storage.class }}
