{{- $protocol := ternary  "https" "http" .Values.config.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KAI_API_LOG_LEVEL: "{{ .Values.adminApi.logLevel }}"
  KAI_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KAI_RELEASE_NAME: "{{ .Release.Name }}"
  KAI_ADMIN_API_BASE_URL: "{{ $protocol }}://{{ .Values.adminApi.host }}"
  KAI_ADMIN_CORS_ENABLED: "{{ .Values.config.admin.corsEnabled }}"
  KAI_SERVICES_K8S_MANAGER: "{{ include "k8s-manager.fullname" . }}:50051"
  KAI_SERVICES_NATS_MANAGER: "{{ include "nats-manager.fullname" . }}:50051"
  KAI_BASE_DOMAIN_NAME: "{{ .Values.config.baseDomainName }}"
  KAI_ADMIN_API_PORT: "8080"
  # Keycloak
  KAI_KEYCLOAK_BASE_URL: "http://{{ include "keycloak.fullname" . }}:{{ .Values.keycloak.service.ports.http }}"
  KAI_KEYCLOAK_MASTER_REALM: "master"
  KAI_KEYCLOAK_REALM: "{{ .Values.keycloak.realmName }}"
  KAI_KEYCLOAK_ADMIN_CLIENT_ID: "{{ .Values.keycloak.adminApi.oidcClient.clientId }}"
  # Registry
  KAI_REGISTRY_HOST: "{{ .Values.registry.host }}"
  KAI_REGISTRY_AUTH_SECRET_NAME: "{{ include "registry.auth.secretName" . }}"
  # MinIO
  KAI_MINIO_ENDPOINT_URL: "{{ include "minio.fullname" .Subcharts.minio }}:{{ .Values.minio.service.port }}"
  KAI_MINIO_REGION: {{ include "minio-config.region" . }}
  # MinIO Tier
  KAI_MINIO_TIER_ENABLED: "{{ .Values.config.minio.tier.enabled }}"
  KAI_MINIO_TIER_NAME: {{ include "minio-config.tier.name" . }}
  # Loki
  KAI_LOKI_ADDRESS: {{ include "loki.url" . }}
  # Prometheus
  KAI_PROMETHEUS_ADDRESS: {{ include "prometheus.url" . }}
  # Redis
  KAI_REDIS_MASTER_ADDRESS: {{ include "redis.master.url" . }}
  {{- if or (eq .Values.redis.architecture "replication")  (eq .Values.config.redis.architecture "replication") }}
  KAI_REDIS_REPLICAS_ADDRESS: {{ include "redis.replicas.url" . }}
  {{- end }}
