apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-api.fullname" . }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAI_REGISTRY_BASIC_AUTH: "{{ include "registry.auth.user" . }}:{{ include "registry.auth.password" . }}"
