test-runtime-api:
  stage: test
  image: golang:1.13
  script:
    - cd runtime/runtime-api
    - go get -u github.com/jstemmer/go-junit-report
    - go test ./... -cover -v -coverprofile=runtime-api-coverage.out 2>&1 | tee -a report.out
    - cat report.out | go-junit-report > runtime-api-report.xml
  coverage: /coverage:\s(\d+(?:\.\d+)?%)/
  artifacts:
    paths:
      - runtime/runtime-api/runtime-api-coverage.out
    reports:
      junit: runtime/runtime-api/runtime-api-report.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - runtime/runtime-api/**/*

sonar-runtime-api:
  extends: .sonar-scanner
  variables:
    SONAR_TOKEN: $SONAR_TOKEN_RUNTIME_API
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/runtime/runtime-api/.sonar"
    COMPONENT_PATH: runtime/runtime-api
    GIT_DEPTH: "0"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - runtime/runtime-api/**/*

release-runtime-api:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix runtime/runtime-api
  script:
    - cd runtime/runtime-api && npx semantic-release -e semantic-release-monorepo
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
      changes:
        - runtime/runtime-api/**/*
        - .gitlab-ci.yml

publish-runtime-api-image:
  stage: publish-image
  image: docker:19
  services:
    - name: docker:19.03.6-dind
      command: ["--experimental"]

  variables:
    IMAGE_PROJECT_NAME: "konstellation/kre-runtime-api"
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    BUILDX_BUILDER: multiarch
    BUILDX_PLATFORM: "linux/amd64,linux/arm64"
  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container --name ${BUILDX_BUILDER} --platform=${BUILDX_PLATFORM}
    - docker buildx inspect --bootstrap ${BUILDX_BUILDER}
    - docker buildx ls
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - TAG=${CI_COMMIT_TAG#runtime-api-v}
    - docker buildx build --push --platform ${BUILDX_PLATFORM}
      --tag $IMAGE_PROJECT_NAME:$TAG
      --tag $IMAGE_PROJECT_NAME:latest
      runtime/runtime-api
  rules:
    - if: '$CI_COMMIT_TAG =~ /^runtime-api-v\d*.\d*.\d*$/'
      when: always
