apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: runtime-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runtime.labels" . | nindent 6 }}
      app: runtime-api
  template:
    metadata:
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
        app: runtime-api
    spec:
      serviceAccountName: kre-operator
      containers:
        - name: runtime-api
          image: konstellation/kre-runtime-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
