apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Chart.Name }}-admin-api
data:
  # Admin
  KRE_ADMIN_API_ADDRESS: "{{.Values.config.admin.apiAddress}}"
  KRE_ADMIN_FRONTEND_BASE_URL: "{{.Values.config.admin.frontendBaseURL}}"
  KRE_ADMIN_CORS_ENABLED: "{{.Values.config.admin.corsEnabled}}"
  # SMTP
  KRE_SMTP_ENABLED: "{{.Values.config.smtp.enabled}}"
  {{- if .Values.config.smtp.enabled}}
  KRE_SMTP_SENDER: "{{.Values.config.smtp.sender}}"
  KRE_SMTP_SENDER_NAME: "{{.Values.config.smtp.senderName}}"
  KRE_SMTP_HOST: "{{.Values.config.smtp.host}}"
  KRE_SMTP_PORT: "{{.Values.config.smtp.port}}"
  {{- end }}
  # Auth
  KRE_AUTH_VERIFICATION_CODE_DURATION_IN_MINUTES: "{{.Values.config.auth.verificationCodeDurationInMinutes}}"
  KRE_AUTH_SESSION_DURATION_IN_HOURS: "{{.Values.config.auth.sessionDurationInHours}}"
  KRE_AUTH_SECURE_COOKIE: "{{.Values.config.auth.secureCookie}}"
  # MongoDB
  KRE_MONGODB_DB_NAME: "{{.Values.mongodb.mongodbDatabase}}"