name: Test Admin API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-patch-version:
    name: Bump patch version before merging main to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
      - name: Bump patch version on all modules using multi-semantic-release
        run: echo "Bump patch version on all modules using multi-semantic-release"

  create-pr-develop:
    name: Create new pull request to develop
    runs-on: ubuntu-latest
    needs: bump-patch-version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: create pull request to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump patch version"
          title: "chore: bump patch version"
          body: "bump patch version"
          branch: "develop"
          base: "main"
          draft: false
