name: github pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
          extended: true

      - name: Install docsy theme submodules
        run: git submodule update --init --recursive

      - name: Install docsy theme dependencies
        working-directory: ./docs
        run: npm install

      - name: Build
        working-directory: ./docs
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          # A destination subdirectory on a publishing branch.
          # We publish to a subfolder because the kre helm charts
          # are deployed into the gh-pages root folder.
          # TODO Move the helm charts repository out of gh-pages.
          destination_dir: site
