name: Test K8S Manager

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - "engine/k8s-manager/**/*"
      - ".github/workflows/test-k8s-manager.yaml"
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/reusable/test.yaml
    with:
      path: engine/k8s-manager
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN_K8S_MANAGER }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
