// Code generated by MockGen. DO NOT EDIT.
// Source: access_control.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/konstellation-io/kai/engine/admin-api/domain/usecase/auth"
)

// MockAccessControl is a mock of AccessControl interface.
type MockAccessControl struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlMockRecorder
}

// MockAccessControlMockRecorder is the mock recorder for MockAccessControl.
type MockAccessControlMockRecorder struct {
	mock *MockAccessControl
}

// NewMockAccessControl creates a new mock instance.
func NewMockAccessControl(ctrl *gomock.Controller) *MockAccessControl {
	mock := &MockAccessControl{ctrl: ctrl}
	mock.recorder = &MockAccessControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControl) EXPECT() *MockAccessControlMockRecorder {
	return m.recorder
}

// CheckGrant mocks base method.
func (m *MockAccessControl) CheckGrant(userID string, resource auth.AccessControlResource, action auth.AccessControlAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGrant", userID, resource, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckGrant indicates an expected call of CheckGrant.
func (mr *MockAccessControlMockRecorder) CheckGrant(userID, resource, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGrant", reflect.TypeOf((*MockAccessControl)(nil).CheckGrant), userID, resource, action)
}
