// Code generated by MockGen. DO NOT EDIT.
// Source: access_control.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kai/engine/admin-api/domain/entity"
	auth "github.com/konstellation-io/kai/engine/admin-api/domain/usecase/auth"
)

// MockAccessControl is a mock of AccessControl interface.
type MockAccessControl struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlMockRecorder
}

// MockAccessControlMockRecorder is the mock recorder for MockAccessControl.
type MockAccessControlMockRecorder struct {
	mock *MockAccessControl
}

// NewMockAccessControl creates a new mock instance.
func NewMockAccessControl(ctrl *gomock.Controller) *MockAccessControl {
	mock := &MockAccessControl{ctrl: ctrl}
	mock.recorder = &MockAccessControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControl) EXPECT() *MockAccessControlMockRecorder {
	return m.recorder
}

// CheckGrants mocks base method.
func (m *MockAccessControl) CheckGrants(user *entity.User, action auth.AccessControlAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGrants", user, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckGrants indicates an expected call of CheckGrants.
func (mr *MockAccessControlMockRecorder) CheckGrants(user, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGrants", reflect.TypeOf((*MockAccessControl)(nil).CheckGrants), user, action)
}

// CheckProductGrants mocks base method.
func (m *MockAccessControl) CheckProductGrants(user *entity.User, product string, action auth.AccessControlAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductGrants", user, product, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckProductGrants indicates an expected call of CheckProductGrants.
func (mr *MockAccessControlMockRecorder) CheckProductGrants(user, product, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductGrants", reflect.TypeOf((*MockAccessControl)(nil).CheckProductGrants), user, product, action)
}

// IsAdmin mocks base method.
func (m *MockAccessControl) IsAdmin(user *entity.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockAccessControlMockRecorder) IsAdmin(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockAccessControl)(nil).IsAdmin), user)
}
