// Code generated by MockGen. DO NOT EDIT.
// Source: process_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProcessRegistry is a mock of ProcessRegistry interface.
type MockProcessRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRegistryMockRecorder
}

// MockProcessRegistryMockRecorder is the mock recorder for MockProcessRegistry.
type MockProcessRegistryMockRecorder struct {
	mock *MockProcessRegistry
}

// NewMockProcessRegistry creates a new mock instance.
func NewMockProcessRegistry(ctrl *gomock.Controller) *MockProcessRegistry {
	mock := &MockProcessRegistry{ctrl: ctrl}
	mock.recorder = &MockProcessRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRegistry) EXPECT() *MockProcessRegistryMockRecorder {
	return m.recorder
}

// RegisterProcess mocks base method.
func (m *MockProcessRegistry) RegisterProcess(ctx context.Context, product, version, process string, src io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterProcess", ctx, product, version, process, src)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterProcess indicates an expected call of RegisterProcess.
func (mr *MockProcessRegistryMockRecorder) RegisterProcess(ctx, product, version, process, src interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProcess", reflect.TypeOf((*MockProcessRegistry)(nil).RegisterProcess), ctx, product, version, process, src)
}

// MockProcessRepository is a mock of ProcessRepository interface.
type MockProcessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRepositoryMockRecorder
}

// MockProcessRepositoryMockRecorder is the mock recorder for MockProcessRepository.
type MockProcessRepositoryMockRecorder struct {
	mock *MockProcessRepository
}

// NewMockProcessRepository creates a new mock instance.
func NewMockProcessRepository(ctrl *gomock.Controller) *MockProcessRepository {
	mock := &MockProcessRepository{ctrl: ctrl}
	mock.recorder = &MockProcessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRepository) EXPECT() *MockProcessRepositoryMockRecorder {
	return m.recorder
}

// CreateProcess mocks base method.
func (m *MockProcessRepository) CreateProcess() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProcess")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProcess indicates an expected call of CreateProcess.
func (mr *MockProcessRepositoryMockRecorder) CreateProcess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProcess", reflect.TypeOf((*MockProcessRepository)(nil).CreateProcess))
}
