// Code generated by MockGen. DO NOT EDIT.
// Source: process_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kai/engine/admin-api/domain/entity"
)

// MockProcessRepository is a mock of ProcessRepository interface.
type MockProcessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRepositoryMockRecorder
}

// MockProcessRepositoryMockRecorder is the mock recorder for MockProcessRepository.
type MockProcessRepositoryMockRecorder struct {
	mock *MockProcessRepository
}

// NewMockProcessRepository creates a new mock instance.
func NewMockProcessRepository(ctrl *gomock.Controller) *MockProcessRepository {
	mock := &MockProcessRepository{ctrl: ctrl}
	mock.recorder = &MockProcessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRepository) EXPECT() *MockProcessRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProcessRepository) Create(ctx context.Context, registry string, newRegisteredProcess *entity.RegisteredProcess) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, registry, newRegisteredProcess)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProcessRepositoryMockRecorder) Create(ctx, registry, newRegisteredProcess interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProcessRepository)(nil).Create), ctx, registry, newRegisteredProcess)
}

// CreateIndexes mocks base method.
func (m *MockProcessRepository) CreateIndexes(ctx context.Context, registry string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexes", ctx, registry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndexes indicates an expected call of CreateIndexes.
func (mr *MockProcessRepositoryMockRecorder) CreateIndexes(ctx, registry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexes", reflect.TypeOf((*MockProcessRepository)(nil).CreateIndexes), ctx, registry)
}

// Delete mocks base method.
func (m *MockProcessRepository) Delete(ctx context.Context, registry, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, registry, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProcessRepositoryMockRecorder) Delete(ctx, registry, imageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProcessRepository)(nil).Delete), ctx, registry, imageID)
}

// GetByID mocks base method.
func (m *MockProcessRepository) GetByID(ctx context.Context, registry, imageID string) (*entity.RegisteredProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, registry, imageID)
	ret0, _ := ret[0].(*entity.RegisteredProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProcessRepositoryMockRecorder) GetByID(ctx, registry, imageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProcessRepository)(nil).GetByID), ctx, registry, imageID)
}

// GlobalSearch mocks base method.
func (m *MockProcessRepository) GlobalSearch(ctx context.Context, filter *entity.SearchFilter) ([]*entity.RegisteredProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalSearch", ctx, filter)
	ret0, _ := ret[0].([]*entity.RegisteredProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalSearch indicates an expected call of GlobalSearch.
func (mr *MockProcessRepositoryMockRecorder) GlobalSearch(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalSearch", reflect.TypeOf((*MockProcessRepository)(nil).GlobalSearch), ctx, filter)
}

// SearchByProduct mocks base method.
func (m *MockProcessRepository) SearchByProduct(ctx context.Context, product string, filter *entity.SearchFilter) ([]*entity.RegisteredProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByProduct", ctx, product, filter)
	ret0, _ := ret[0].([]*entity.RegisteredProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByProduct indicates an expected call of SearchByProduct.
func (mr *MockProcessRepositoryMockRecorder) SearchByProduct(ctx, product, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByProduct", reflect.TypeOf((*MockProcessRepository)(nil).SearchByProduct), ctx, product, filter)
}

// Update mocks base method.
func (m *MockProcessRepository) Update(ctx context.Context, registry string, newRegisteredProcess *entity.RegisteredProcess) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, registry, newRegisteredProcess)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProcessRepositoryMockRecorder) Update(ctx, registry, newRegisteredProcess interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProcessRepository)(nil).Update), ctx, registry, newRegisteredProcess)
}
