// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kai/engine/admin-api/domain/entity"
)

// MockK8sService is a mock of K8sService interface.
type MockK8sService struct {
	ctrl     *gomock.Controller
	recorder *MockK8sServiceMockRecorder
}

// MockK8sServiceMockRecorder is the mock recorder for MockK8sService.
type MockK8sServiceMockRecorder struct {
	mock *MockK8sService
}

// NewMockK8sService creates a new mock instance.
func NewMockK8sService(ctrl *gomock.Controller) *MockK8sService {
	mock := &MockK8sService{ctrl: ctrl}
	mock.recorder = &MockK8sServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8sService) EXPECT() *MockK8sServiceMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockK8sService) Publish(runtimeID string, version *entity.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", runtimeID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockK8sServiceMockRecorder) Publish(runtimeID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockK8sService)(nil).Publish), runtimeID, version)
}

// Start mocks base method.
func (m *MockK8sService) Start(ctx context.Context, runtimeID string, version *entity.Version, versionConfig *entity.VersionConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, runtimeID, version, versionConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockK8sServiceMockRecorder) Start(ctx, runtimeID, version, versionConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockK8sService)(nil).Start), ctx, runtimeID, version, versionConfig)
}

// Stop mocks base method.
func (m *MockK8sService) Stop(ctx context.Context, runtimeID string, version *entity.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, runtimeID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockK8sServiceMockRecorder) Stop(ctx, runtimeID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockK8sService)(nil).Stop), ctx, runtimeID, version)
}

// Unpublish mocks base method.
func (m *MockK8sService) Unpublish(runtimeID string, version *entity.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", runtimeID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockK8sServiceMockRecorder) Unpublish(runtimeID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockK8sService)(nil).Unpublish), runtimeID, version)
}

// UpdateConfig mocks base method.
func (m *MockK8sService) UpdateConfig(runtimeID string, version *entity.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", runtimeID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockK8sServiceMockRecorder) UpdateConfig(runtimeID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockK8sService)(nil).UpdateConfig), runtimeID, version)
}

// WatchProcessStatus mocks base method.
func (m *MockK8sService) WatchProcessStatus(ctx context.Context, runtimeID, versionName string) (<-chan *entity.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchProcessStatus", ctx, runtimeID, versionName)
	ret0, _ := ret[0].(<-chan *entity.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchProcessStatus indicates an expected call of WatchProcessStatus.
func (mr *MockK8sServiceMockRecorder) WatchProcessStatus(ctx, runtimeID, versionName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchProcessStatus", reflect.TypeOf((*MockK8sService)(nil).WatchProcessStatus), ctx, runtimeID, versionName)
}
