// Code generated by MockGen. DO NOT EDIT.
// Source: user_registry.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/konstellation-io/kai/engine/admin-api/domain/service/auth"
)

// MockUserRegistry is a mock of UserRegistry interface.
type MockUserRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockUserRegistryMockRecorder
}

// MockUserRegistryMockRecorder is the mock recorder for MockUserRegistry.
type MockUserRegistryMockRecorder struct {
	mock *MockUserRegistry
}

// NewMockUserRegistry creates a new mock instance.
func NewMockUserRegistry(ctrl *gomock.Controller) *MockUserRegistry {
	mock := &MockUserRegistry{ctrl: ctrl}
	mock.recorder = &MockUserRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRegistry) EXPECT() *MockUserRegistryMockRecorder {
	return m.recorder
}

// AddProductGrants mocks base method.
func (m *MockUserRegistry) AddProductGrants(ctx context.Context, userEmail, product string, grants []auth.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductGrants", ctx, userEmail, product, grants)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProductGrants indicates an expected call of AddProductGrants.
func (mr *MockUserRegistryMockRecorder) AddProductGrants(ctx, userEmail, product, grants interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductGrants", reflect.TypeOf((*MockUserRegistry)(nil).AddProductGrants), ctx, userEmail, product, grants)
}

// CreateGroupWithPolicy mocks base method.
func (m *MockUserRegistry) CreateGroupWithPolicy(ctx context.Context, name, policy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupWithPolicy", ctx, name, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroupWithPolicy indicates an expected call of CreateGroupWithPolicy.
func (mr *MockUserRegistryMockRecorder) CreateGroupWithPolicy(ctx, name, policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupWithPolicy", reflect.TypeOf((*MockUserRegistry)(nil).CreateGroupWithPolicy), ctx, name, policy)
}

// CreateUserWithinGroup mocks base method.
func (m *MockUserRegistry) CreateUserWithinGroup(ctx context.Context, name, password, group string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithinGroup", ctx, name, password, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserWithinGroup indicates an expected call of CreateUserWithinGroup.
func (mr *MockUserRegistryMockRecorder) CreateUserWithinGroup(ctx, name, password, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithinGroup", reflect.TypeOf((*MockUserRegistry)(nil).CreateUserWithinGroup), ctx, name, password, group)
}

// DeleteGroup mocks base method.
func (m *MockUserRegistry) DeleteGroup(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockUserRegistryMockRecorder) DeleteGroup(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockUserRegistry)(nil).DeleteGroup), ctx, name)
}

// DeleteUser mocks base method.
func (m *MockUserRegistry) DeleteUser(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRegistryMockRecorder) DeleteUser(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRegistry)(nil).DeleteUser), ctx, name)
}

// RevokeProductGrants mocks base method.
func (m *MockUserRegistry) RevokeProductGrants(ctx context.Context, userEmail, product string, grants []auth.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeProductGrants", ctx, userEmail, product, grants)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeProductGrants indicates an expected call of RevokeProductGrants.
func (mr *MockUserRegistryMockRecorder) RevokeProductGrants(ctx, userEmail, product, grants interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeProductGrants", reflect.TypeOf((*MockUserRegistry)(nil).RevokeProductGrants), ctx, userEmail, product, grants)
}
